version: '3'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=url
        ports:
          - "5432:5432"
        volumes:
          - db:/var/lib/postgresql/data
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code

volumes:
  db:
    driver: local
