version: '3'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=url
        ports:
          - "5432:5432"
        volumes:
          - db:/var/lib/postgresql/data

    testdb:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=url
      ports:
        - "5433:5433"
      volumes:
        - db:/var/lib/postgresql/data_test

    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
          - db

volumes:
  db:
    driver: local
